#ifndef XLSTOUSERS_CONFIGPARSER_CMDOPTIONSDEFAULTVALUES_H
#define XLSTOUSERS_CONFIGPARSER_CMDOPTIONSDEFAULTVALUES_H

#include "cmd_options.h"

const std::string DEFAULT_CONFIG_PATH = "/etc/xlstousers/";
const bool DEFAULT_INTERACTIVE = false;
const bool DEFAULT_TEST = false;
const bool DEFAULT_QUOTA = false;

#endif  // XLSTOUSERS_CONFIGPARSER_CMDOPTIONSDEFAULTVALUES_H
