#ifndef XLSTOUSERS_CONFIGPARSER_CMDOPTIONSDEFAULTVALUES_H
#define XLSTOUSERS_CONFIGPARSER_CMDOPTIONSDEFAULTVALUES_H

#include "cmd_options.h"

const auto DEFAULT_CONFIG_PATH = "/etc/xlstousers/";
const auto DEFAULT_INTERACTIVE = false;
const auto DEFAULT_TEST = false;
const auto DEFAULT_QUOTA = false;

#endif  // XLSTOUSERS_CONFIGPARSER_CMDOPTIONSDEFAULTVALUES_H
